### ISSUE TITLE
Requesters other than the base tier does not work

### ISSUE THREAD

**Issue by CinnamonShaey** [gamingnetwork123/atm6#2]
So, the requester from RSrequestify mod works fine, but the 3 tiers of requesters above that from the cable tiers mod does not, so that is the Elite Requester, Ultra Requester and Creative Requester to clarify, they do not remember the number they are set at, they revert back to 0 as soon as you leave the UI rendering them useless

**Comment by zxoltari** [comment]
its prob a bug that is only fixable by the mod author
