### ISSUE TITLE
Bees refund

### ISSUE THREAD

**Issue by Chrispy992** [gamingnetwork123/atm6#3]
Hey Team, 
i heared thats the problems with the bees are solved and i want to ask if its possible to get my lost bees back.
My Beelist:
chaotic bee 8x
awakened bee 8x
draconium bee 2x
wither bee 8x
redstone bee 4x
diamond bee 4x
emerald bee 4x
fluorite bee 1x
lapis bee 3x
allthemodium bee 2x
vibranium bee 2x
unobtainium bee 2x
aluminum bee 1x
certus bee 1x
abbee 1x
copper bee 1x
gold bee 2x
iron bee 3x
lead bee 1x
netherite bee 3x
nickel bee 1x
osmium bee 1x
platinum bee 1x
silver bee 1x
tin bee 1x
obsidian bee 1x
stoned bee 1x
ghastly bee 2x
withered bee 1x
croppy bee 1x
lumber bee 2x
mana bee 2x
mystical bee 1x
sandy bee 2x
stan bee 1x
kobee 1x
slimy bee 2x
oreo bee 1x

**Comment by zxoltari** [comment]
marked work in progress
