### ISSUE TITLE
Lost bee

### ISSUE THREAD

**Issue by CinnamonShaey** [gamingnetwork123/atm6#4]
only lost one, but an expensive one, Chaotic bee, it disappeared after the last crash (or shutdown) so that tells me that the issue of them disappearing is not fixed.... would like that back, and hopefully a fix so bees dont disappear after a crash or whatever is happening with them

**Comment by zxoltari** [comment]
was not on the list added to list all got to do is log on and reload the plugin

**Comment by zxoltari** [comment]
added the missing bee to your inv enjoy

**Comment by CinnamonShaey** [comment]
> added the missing bee to your inv enjoy

no you did not? i must not have picked it up cause i dont have it

**Comment by CinnamonShaey** [comment]
Also lost a kitten bee, so I guess that can be added to the lost too
