### ISSUE TITLE
I might have f'ed the server, needs a roll back to last backup

### ISSUE THREAD

**Issue by CinnamonShaey** [gamingnetwork123/atm6#5]
i placed a block placer and then put a block in that it did not like, instantly crashed and now whenever its starts it just throws me straight out and crashes again

**Comment by zxoltari** [comment]
you are aware of how big the files are right

**Comment by zxoltari** [comment]
it could take weeks at this point to restore it

**Comment by CinnamonShaey** [comment]
yes i know but the world might be corrupted
